repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --indent=2, --no-sort-keys]
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-case-conflict
