#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0, rgba32f) uniform readonly  image2D Input;
layout(binding = 1, rgba32f) uniform writeonly image2D Output;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size  = imageSize(Output);
    if (coord.x >= size.x || coord.y >= size.y) return;
    float height = imageLoad(Input, coord).r;
    imageStore(Output, coord, vec4(0.0, 0.0, 0.0, height));
}
