name: Build PGPatcher

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Build Release
      run: |
        ./buildRelease.ps1

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: pgpatcher-dist-${{ github.sha }}
        path: dist

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pgpatcher-build-${{ github.sha }}
        path: build/bin
